### PR TITLE
Add openzfs-tracking.sh script

### PR DESCRIPTION
**Pull request by behlendorf**
This script is used to dynamically generate the OpenZFS Commit
Tracking page at http://build.zfsonlinux.org/openzfs-tracking.html.

### CODE REVIEW

**Comment by gmelikov** [comment]
I want to add some comments (links to wiki, etc) and table filter by commit status. Is it better to make new PR after this one or add my commit here?

**Comment by behlendorf** [comment]
Improvements are welcome! If you have a better version of the script can you open a new PR with this commit and then your changes applied on top.   Thanks.

**Comment by behlendorf** [comment]
@gmelikov actually let me just merge this since it's functional and useful.  This should make it easier for you to open a new PR with your various improvements.

**Comment by jumbi77** [comment]
Thanks. The auto-gen. HTML page is cool. Maybe one can integrate the 'scripts/openzfs-exceptions.txt' entries with a different color and a note like 'The OpenZFS commit isn't applicable to Linux'. That way every commit/issue is tracked even it is not applicable to ZoL.

And a question: It is right that the following path '_usr/src/uts/common/fs/zfs_'  is twice entered in '_OPENZFS_PATHS='_ and '_usr/src/cmd/mdb/common/modules/zfs_' and '_usr/src/test/zfs-tests_' is missing? Just compare the "Directories of interest for ZFS" in the OpenZFS README.md

**Comment by gmelikov** [comment]
@jumbi77 good idea, i'll try to implement it with another things!

**Pull request merged**
