### PR TITLE
Introduce a performance builder

### PR DESCRIPTION
**Pull request by dinatale2**
Add a builder to run the performance regression
suite. Use an EC2 d2.xlarge instance type since
that has 3 hard drives we can utilize. The new
builder creates a partition on the front portion
of the drive to ensure that the test runs in a
reasonable amount of time.

Signed-off-by: Giuseppe Di Natale <dinatale2@llnl.gov>

### CODE REVIEW

**Comment by dinatale2** [comment]
Still TODO:
- Move partition creation to bb-test-prepare.sh
- Possibly, zero out the partitions in bb-test-prepare.sh

There is also an issue when bb-test-zfstests.sh attempts to perform a module unload in its cleanup routine upon exit that doesn't appear to be related, but definitely needs looking into.

**Comment by dinatale2** [comment]
Updated. Moved the partition creation to bb-test-prepare.sh.

**Comment by dinatale2** [comment]
Updated. Attempting to zero out the partitions created in bb-test-prepare.sh. Also, generalized the logic for partitioning and zeroing.

**Comment by dinatale2** [comment]
Updated. I think everything is all set for a performance builder. I need to look into the cleanup hang, but I'm sure that's not the fault of this pull request. We could wait until that is resolved to pull this in if you'd like.

**Comment by dinatale2** [comment]
One last update, when running dd, use bs=1M for better performance.

**Comment by behlendorf** [comment]
Merged!

**Pull request closed without merging**
